{{- if .Values.receiver.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thanos.receiverIngestor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.receiverIngestor.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "thanos.receiverIngestor.serviceNameHeadless" . }}
  replicas: {{ .Values.receiver.ingestor.replicas }}
  {{- with .Values.receiver.ingestor.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "thanos.receiverIngestor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thanos.receiverIngestor.selectorLabels" . | nindent 8 }}
      {{- with .Values.receiver.ingestor.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.objstoreConfig.create (gt (len .Values.receiver.ingestor.podAnnotations) 0) }}
      annotations:
      {{- if .Values.objstoreConfig.create }}
        checksum/config: {{ include "thanos.objstoreConfigHash" . }}
      {{- end }}
      {{- with .Values.receiver.ingestor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thanos.receiverIngestor.serviceAccountName" . }}
      {{- with .Values.receiver.ingestor.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.receiver.ingestor.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.receiver.ingestor.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        - name: thanos-receiver-ingestor
          {{- with .Values.receiver.ingestor.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "thanos.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{- with .Values.receiver.ingestor.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - receive
            - --log.level={{ .Values.logLevel }}
            - --log.format={{ .Values.logFormat }}
            - {{ printf "--grpc-address=0.0.0.0:%d" (int .Values.receiver.ingestor.containerPorts.grpc) }}
            - {{ printf "--http-address=0.0.0.0:%d" (int .Values.receiver.ingestor.containerPorts.http) }}
            - {{ printf "--remote-write.address=0.0.0.0:%d" (int .Values.receiver.httpRemoteWritePort) }}
            - --objstore.config-file={{ include "thanos.objstoreConfigMountPath" . }}
          {{- if .Values.autoGomemlimit.enabled }}
            - --enable-auto-gomemlimit
          {{- with .Values.autoGomemlimit.ratio }}
            - --auto-gomemlimit.ratio={{ . }}
          {{- end }}
          {{- end }}
            - --tsdb.path=/var/thanos/receive
            - --tsdb.retention={{ .Values.receiver.retention }}
            - --label=receive_replica="$(NAME)"
            - {{ printf "--receive.local-endpoint=$(NAME).%s.%s-headless.svc.%s:%d" (include "thanos.receiverIngestor.fullname" .) .Release.Namespace .Values.clusterDomain (int .Values.receiver.ingestor.service.ports.grpc) }}
          {{- with .Values.receiver.ingestor.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: grpc
              protocol: TCP
              containerPort: {{ .Values.receiver.ingestor.containerPorts.grpc }}
            - name: http
              protocol: TCP
              containerPort: {{ .Values.receiver.ingestor.containerPorts.http }}
            - name: http-rem-write
              protocol: TCP
              containerPort: {{ .Values.receiver.httpRemoteWritePort }}
          livenessProbe:
            {{- toYaml .Values.receiver.ingestor.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.receiver.ingestor.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: objstore-config
              mountPath: {{ include "thanos.objstoreConfigMountPath" . }}
              subPath: {{ .Values.objstoreConfig.key }}
              readOnly: true
            - name: data
              mountPath: /var/thanos/receive
              readOnly: false
          {{- with .Values.receiver.ingestor.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.receiver.ingestor.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.receiver.ingestor.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: objstore-config
          secret:
            secretName: {{ include "thanos.objstoreConfigSecretName" . }}
      {{- if not .Values.receiver.ingestor.persistence.enabled }}
        - name: data
          emptyDir: {}
      {{- end }}
      {{- with .Values.receiver.ingestor.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "shared.nodeSelector" (dict "component" .Values.receiver.ingestor "commons" .Values.components)) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "shared.affinity" (dict "component" .Values.receiver.ingestor "commons" .Values.components)) }}
      affinity:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "shared.topologySpreadConstraints" (dict "component" .Values.receiver.ingestor "commons" .Values.components)) }}
      topologySpreadConstraints:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "shared.tolerations" (dict "component" .Values.receiver.ingestor "commons" .Values.components)) }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
  {{- if .Values.receiver.ingestor.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "thanos.receiverIngestor.selectorLabels" . | nindent 10 }}
        {{- with .Values.receiver.ingestor.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.receiver.ingestor.persistence.storageClass }}
        storageClassName: {{ .Values.receiver.ingestor.persistence.storageClass }}
        {{- end }}
        accessModes:
          - {{ .Values.receiver.ingestor.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.receiver.ingestor.persistence.size }}
  {{- if (eq (include "shared.pvc.persistentVolumeClaimRetentionPolicySupported" .) "true") }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ ternary "Retain" "Delete" .Values.receiver.ingestor.persistence.retainDeleted }}
    whenScaled: {{ ternary "Retain" "Delete" .Values.receiver.ingestor.persistence.retainScaled }}
  {{- end }}
  {{- end }}
{{- end -}}
