{{- if and .Values.ruler.enabled .Values.ruler.rules.create -}}
{{- if not .Values.ruler.rules.value }} {{- fail "ruler.rules.value must be set when rules is enabled and ruler.rules.create is set to true (default value)" }} {{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos.ruler.rulesConfigmapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.ruler.labels" . | nindent 4 }}
data:
  rules.yaml: |-
    {{- .Values.ruler.rules.value | nindent 4 }}
{{- end -}}
