{{- if .Values.objstoreConfig.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thanos.objstoreConfigSecretName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.objstoreConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "shared.labels" . | nindent 4 }}
data:
  {{ .Values.objstoreConfig.key }}: |-
  {{- with .Values.objstoreConfig.value }}
  {{- if kindIs "string" . }}
    {{- tpl . $ | b64enc | nindent 4 }}
  {{- else }}
    {{- toYaml . | b64enc | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end -}}
