{{- if .Values.bucketweb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.bucketweb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.bucketweb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.bucketweb.autoscaling.enabled }}
  replicas: {{ .Values.bucketweb.replicas }}
  {{- end }}
  {{- with .Values.bucketweb.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "thanos.bucketweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thanos.bucketweb.selectorLabels" . | nindent 8 }}
      {{- with .Values.bucketweb.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bucketweb.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thanos.bucketweb.serviceAccountName" . }}
      {{- with .Values.bucketweb.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bucketweb.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.bucketweb.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      containers:
        - name: thanos-bucketweb
          {{- with .Values.bucketweb.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "thanos.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{- with .Values.bucketweb.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - tools
            - bucket
            - web
            - --log.level={{ .Values.logLevel }}
            - --log.format={{ .Values.logFormat }}
            - {{ printf "--http-address=0.0.0.0:%d" (int .Values.bucketweb.containerPorts.http) }}
            - --objstore.config-file={{ include "thanos.objstoreConfigMountPath" . }}
            {{- if .Values.autoGomemlimit.enabled }}
            - --enable-auto-gomemlimit
            {{- with .Values.autoGomemlimit.ratio }}
            - --auto-gomemlimit.ratio={{ . }}
            {{- end }}
            {{- end }}
            {{- if .Values.bucketweb.refresh }}
            - --refresh={{ .Values.bucketweb.refresh}}
            {{- end }}
            {{- if .Values.bucketweb.timeout }}
            - --timeout={{ .Values.bucketweb.timeout }}
            {{- end }}
            {{- with .Values.bucketweb.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.bucketweb.containerPorts.http }}
          livenessProbe:
            {{- toYaml .Values.bucketweb.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.bucketweb.readinessProbe | nindent 12 }}
          volumeMounts:
            - mountPath: {{ include "thanos.objstoreConfigMountPath" . }}
              name: objstore-config
              subPath: {{ .Values.objstoreConfig.key }}
              readOnly: true
          {{- with .Values.bucketweb.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.bucketweb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.bucketweb.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: objstore-config
          secret:
            secretName: {{ include "thanos.objstoreConfigSecretName" . }}
      {{- with .Values.bucketweb.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "shared.nodeSelector" (dict "component" .Values.bucketweb "commons" .Values.components)) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "shared.affinity" (dict "component" .Values.bucketweb "commons" .Values.components)) }}
      affinity:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "shared.topologySpreadConstraints" (dict "component" .Values.bucketweb "commons" .Values.components)) }}
      topologySpreadConstraints:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with (include "shared.tolerations" (dict "component" .Values.bucketweb "commons" .Values.components)) }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
{{- end -}}
