apiVersion: v2
name: minio
description: |
  A Helm chart for MinIO. See the full [changelog](https://github.com/solidcharts/helm-charts/blob/main/charts/minio/CHANGELOG.md) and [readme](https://github.com/solidcharts/helm-charts/blob/main/charts/minio/README.md).
type: application
version: 0.4.1
appVersion: "RELEASE.2025-09-07T16-13-09Z"
icon: https://raw.githubusercontent.com/solidcharts/helm-charts/main/charts/minio/icon.svg
sources:
  - https://github.com/solidcharts/helm-charts/
maintainers:
  - name: pnowy
    email: solidcharts@przemeknowak.com
dependencies:
  - name: shared
    version: 0.X.X
    repository: oci://ghcr.io/solidcharts/helm-charts
