apiVersion: v2
name: minio
description: |
  A Helm chart for MinIO.
type: application
version: 0.5.0
appVersion: "RELEASE.2025-10-15T17-29-55Z"
icon: https://raw.githubusercontent.com/solidcharts/helm-charts/main/charts/minio/icon.svg
sources:
  - https://github.com/solidcharts/helm-charts/
maintainers:
  - name: pnowy
    email: solidcharts@przemeknowak.com
dependencies:
  - name: shared
    version: 0.X.X
    repository: oci://ghcr.io/solidcharts/helm-charts
