apiVersion: v2
name: shared
description: |
  A Helm chart library for solidcharts.
type: library
version: 0.3.2
sources:
  - https://github.com/solidcharts/helm-charts/
maintainers:
  - name: pnowy
    email: solidcharts@przemeknowak.com
