apiVersion: v2
name: shared
description: |
  A Helm chart library for solidcharts. See the full [changelog](https://github.com/solidcharts/helm-charts/blob/main/charts/shared/CHANGELOG.md) and [readme](https://github.com/solidcharts/helm-charts/blob/main/charts/shared/README.md).
type: library
version: 0.3.1
sources:
  - https://github.com/solidcharts/helm-charts/
maintainers:
  - name: pnowy
    email: solidcharts@przemeknowak.com
