apiVersion: v2
name: thanos
description: |
  Thanos Helm chart for Kubernetes.
type: application
version: 0.7.0
appVersion: v0.40.1
keywords:
  - kubernetes
  - thanos
  - prometheus
  - monitoring
  - alerting
  - metrics
home: https://thanos.io/
icon: https://raw.githubusercontent.com/solidcharts/helm-charts/main/charts/thanos/icon.png
sources:
  - https://github.com/thanos-io/thanos
  - https://github.com/thanos-io/kube-thanos
  - https://github.com/solidcharts/helm-charts/
maintainers:
  - name: pnowy
    email: solidcharts@przemeknowak.com
dependencies:
  - name: shared
    version: 0.X.X
    repository: oci://ghcr.io/solidcharts/helm-charts
