{{- if and .Values.query.enabled .Values.query.ingress.enabled -}}
{{- $apiIsStable := eq (include "shared.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "shared.ingress.supportsPathType" .) "true" -}}
{{- $serviceName := include "thanos.query.fullname" . -}}
{{- include "thanos.ingress.checkParams" (dict "componentPath" "query" "ingress" .Values.query.ingress) }}
apiVersion: {{ include "shared.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.query.labels" . | nindent 4 }}
  {{- with .Values.query.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if and $apiIsStable .Values.query.ingress.ingressClassName }}
  ingressClassName: {{ .Values.query.ingress.ingressClassName }}
{{- end }}
  rules:
  {{- range .Values.query.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  name: http
              {{- else }}
                serviceName: {{ $serviceName }}
                servicePort: http
              {{- end }}
          {{- end }}
  {{- end }}
{{- if .Values.query.ingress.tls }}
  tls:
  {{- range .Values.query.ingress.tls }}
    - hosts:
    {{- range .hosts }}
        - {{ quote . }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- end }}
