apiVersion: v2
name: rabbitmq
description: |
  A Helm chart for RabbitMQ.
type: application
version: 0.5.0
appVersion: "4.2.0-management"
icon: https://raw.githubusercontent.com/solidcharts/helm-charts/main/charts/rabbitmq/icon.png
sources:
  - https://github.com/solidcharts/helm-charts/
maintainers:
  - name: pnowy
    email: solidcharts@przemeknowak.com
dependencies:
  - name: shared
    version: 0.X.X
    repository: oci://ghcr.io/solidcharts/helm-charts
